### ISSUE TITLE
Release updated quick start image

### ISSUE THREAD

**Issue by bobbywatson3** [bastionzero/charts#14]
The quick start code has been updated, but a new docker image has not been pushed.

**Comment by lipmas** [comment]
@bobbywatson3 Thanks for the reminder. I just pushed a new quickstart image `2.1.1` to docker hub and updated the chart again to use this image by default in https://github.com/bastionzero/charts/pull/15

**Comment by bobbywatson3** [comment]
Perfect, thanks!
